Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.11/site-packages/myst_nb/core/execute/inline.py", line 128, in code_cell_outputs
    self._client.execute_cell(
  File "/opt/anaconda3/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 173, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/anaconda3/lib/python3.11/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from scipy.linalg import eig

A = np.array([[0.95, 0, 0.15],[0.05,0.8,0],[0,0.2,0.85]])

eigenvalues, eigenvectors = ## Your code here
------------------


[0;36m  Cell [0;32mIn[7], line 5[0;36m[0m
[0;31m    eigenvalues, eigenvectors = ## Your code here[0m
[0m                                ^[0m
[0;31mSyntaxError[0m[0;31m:[0m invalid syntax


