Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.11/site-packages/myst_nb/core/execute/inline.py", line 128, in code_cell_outputs
    self._client.execute_cell(
  File "/opt/anaconda3/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 173, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/anaconda3/lib/python3.11/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from python_environment_check import check_packages


d = {
    'numpy': '1.21.2',
    'matplotlib': '3.4.3',
    'sklearn': '1.0',
    'pandas': '1.3.2'
}
check_packages(d)
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [0;32mIn[2], line 1[0m
[0;32m----> 1[0m [38;5;28;01mfrom[39;00m [38;5;21;01mpython_environment_check[39;00m [38;5;28;01mimport[39;00m check_packages
[1;32m      4[0m d [38;5;241m=[39m {
[1;32m      5[0m     [38;5;124m'[39m[38;5;124mnumpy[39m[38;5;124m'[39m: [38;5;124m'[39m[38;5;124m1.21.2[39m[38;5;124m'[39m,
[1;32m      6[0m     [38;5;124m'[39m[38;5;124mmatplotlib[39m[38;5;124m'[39m: [38;5;124m'[39m[38;5;124m3.4.3[39m[38;5;124m'[39m,
[1;32m      7[0m     [38;5;124m'[39m[38;5;124msklearn[39m[38;5;124m'[39m: [38;5;124m'[39m[38;5;124m1.0[39m[38;5;124m'[39m,
[1;32m      8[0m     [38;5;124m'[39m[38;5;124mpandas[39m[38;5;124m'[39m: [38;5;124m'[39m[38;5;124m1.3.2[39m[38;5;124m'[39m
[1;32m      9[0m }
[1;32m     10[0m check_packages(d)

[0;31mModuleNotFoundError[0m: No module named 'python_environment_check'

